### ISSUE TITLE
Global Security Vulnerability Summit

### ISSUE THREAD

**Issue by joshbressers** [cloudsecurityalliance/gsd-project#15]
The CNCF is hosting a Global Security Vulnerability Summit at the Open Source Summit

https://events.linuxfoundation.org/open-source-summit-north-america/

Let's use this issue to track how the GSD plans to interact with this summit. There will be a CFP at some point in the future.

# Planning to attend
* Josh Bressers (Anchore)

# Possible presentations

**Comment by athix** [comment]
I plan on attending as well.

**Comment by joshbuker** [comment]
The GSVS has already happened, closing.
