### ISSUE TITLE
GitHub repo consolidation

### ISSUE THREAD

**Issue by kurtseifried** [cloudsecurityalliance/gsd-project#6]
As discussed at the meeting we need to consolidate the GSD repos, in broad terms we want to keep:
gsd-database (actual GSD data)gsd-project-plans (Policy and higher-level stuff)gsd-tools (software/tools)
get to stay and everything else gets merged or removed:
gsd-datavalues - CWE type data, this should probably live in a directory in the gsd-database?
gsd-objects - data about researchers/projects/etc intended for confidence scoring - this should probably be moved into the gsd-database?

gsd-demo - this should probably be moved into gsd-tools?
gsd-api-demo - this should probably be moved into gsd-tools?

gsd-experimental - should be merged into gsd-project-plans

gsd-url-processing - some experimental work, should be merged into gsd-tools

gsd-url-downloads - experimental copy of URL data, this definitely needs to go away, I've emailed the Internet Archive about buying their private URL mirroring service but no reply. This should probably be moved into an S3 bucket (requestor pays?)

gsd-url-list - experimental data, this should go away asap (it's basically just URL's extracted from the GSD dataset)
Thoughts/comments?

**Comment by TheFoxAtWork** [comment]
i would recommend moving gsd-api-demo & gsd-demo into gsd-project-plans as it is not a specific tool but rather to demonstrate the capabilities of gsd.  As the project is updated, the demo will change

i agree with all other recommendations.

**Comment by kurtseifried** [comment]
cloudsecurityalliance/gsd-datavalues data sent via PR and issues transfered.

**Comment by kurtseifried** [comment]
cloudsecurityalliance/gsd-objects issue merged and repo deleted

**Comment by kurtseifried** [comment]
cloudsecurityalliance/gsd-url-list scrapped as per plan

**Comment by kurtseifried** [comment]
gsd-url-processing merged into gsd-tools as per plan

**Comment by kurtseifried** [comment]
gsd-url-downloads renamed to obsolete-gsd-url-downloads

**Comment by kurtseifried** [comment]
gsd-experimental data and issues moved to gsd-project-plans as per plan

**Comment by kurtseifried** [comment]
> i would recommend moving gsd-api-demo & gsd-demo into gsd-project-plans as it is not a specific tool but rather to demonstrate the capabilities of gsd. As the project is updated, the demo will change
> 
> i agree with all other recommendations.

@athix what are your thoughts? I think your tool is mature enough it should go into gsd-tools, and it is definitely a tool we plan to use (at least initially), is it safe to merge in, or do we want it separate or?

**Comment by athix** [comment]
@kurtseifried @TheFoxAtWork 

I'm fine with merging it into either repo personally. My thoughts are that it can either be the base for the API and UI code, or we can toss it wholesale if a better solution is found.

My $0.02 would be to merge it into the tools repo for now, and if we want to replace it with a different solution down the line then it should be easy enough to wipe the folder and replace it with the new code. The human readable part I think we can be flexible on how it works during these early stages, while the machine readable API we may want to define sooner rather than later so that other tools can rely on a stable interface to begin building out the second order toolings.

**Comment by kurtseifried** [comment]
I actually think it's a bad idea to set the expectation of a static data format. This is one of the things slowly killing CVE (static data and many tools that are not evolving very rapidly). I would also suggest if we want "static" we provide that as an option (e.g. a translation layer) but behind the scenes we actually keep moving forwards (if the market really wants this they can ask for it, but I'm not spending effort from the start providing it, I don't even know if it's needed). 

Also that's for the GSD namespace, we don't control any other namespace, so hopefully that factor also helps encourage consumers of GSD data to be nimble.

**Comment by athix** [comment]
Having stable APIs is critical to building out the tooling around this, at least from a dev perspective. Having a rapid development pace is fine, but you can't just break the API out of nowhere or you'll quickly drive people away from relying on it. In short: follow [semver](https://semver.org) and provide a reasonable timeframe for downstream developers to upgrade to new major versions. Avoid major version bumps whenever possible, while being willing to make breaking changes when there is real benefit to be had.

**Comment by kurtseifried** [comment]
I think more generally what I'm saying is I don't think we have to invent another data format, and I don't think we should.

E.g. we currently use the OSV data format in the GSD namespace (which is definitely better for opensource/git style world than the CVE JSON I invented). I think the expectation should be we use other well known data format(s) such as the ones listed in https://github.com/cloudsecurityalliance/gsd-project-plans/blob/main/data-formats/Thoughts-on-data-formats.md , especially as we may have vulnerabilities, but also incidents or malware which have their own (better, more specific) data formats. To say nothing of the stuff other people put in their own namespaces.

Basically, we punt on this and trust that OSV/etc will be good stewards. One problem can be the slowness, to the point where some data formats have already been supplanted by others because they moved so slow (everything that was XML based). 

Long term maybe we invent another data format, but I don't want to until there is a clear need, for now, let's outsource/abstract it away to others who specialize in it.

**Comment by athix** [comment]
After giving it some more thought, I think I'll go with Emily's suggestion and put it into the project plans repo. If we want to use it as the basis for the actual implementation, we can always move it over to the tools repo then. Until then, keep it clearly labeled as the demo and sorted appropriately.

**Comment by kurtseifried** [comment]
gsd-project-plans also renamed to gsd-project

**Comment by kurtseifried** [comment]
tool merged into gsd-project and original repos deleted.

**Comment by kurtseifried** [comment]
this leaves the repo of url mirror data which is to big to merge in to anything so closing for now.
